g++ -g -c shapes.cpp
g++ -g -c hormigas.cpp
g++ -g -c NDominatedSet.cpp
g++ -g -c macs.cpp
g++ -g -c main.cpp
g++ -g -c aco.cpp
g++ -g -c utils.cpp
g++ -o exe main.o macs.o shapes.o hormigas.o NDominatedSet.o aco.o utils.o
